'use strict'

var hetzblocker = hetzblocker || {} // eslint-disable-line no-use-before-define
hetzblocker.common = hetzblocker.common || {}
hetzblocker.common.domainlist = (function () {
  return {
    listedDomains: [
      'amiado.com',
      'amiadogroup.com',
      'antenne.de',
      'antenne1.de',
      'api-co.la.welt.de',
      'artcollector-magazin.de',
      'artinvestor.de',
      'as-konzerneinkauf.de',
      'asv.de',
      'audiovideofotobild.de',
      'aufeminin.com',
      'auto-bild.ro',
      'auto-swiat.pl',
      'auto-wirtschaft.ch',
      'auto.cz',
      'autobahn.eu',
      'autobild.com.mx',
      'autobild.de',
      'autobild.es',
      'autobild.fi',
      'autobild.ge',
      'autobild.gr',
      'autobild.hu',
      'autobild.in',
      'autobild.lt',
      'autobild.si',
      'autobild.tv',
      'autobild.ua',
      'autobildallrad.de',
      'autobildindonesia.com',
      'autoexpress.co.uk',
      'autohaus24.de',
      'autojournal.fr',
      'autoleht.ee',
      'autoplus.fr',
      'autoshow.com.tr',
      'autotip.auto.cz',
      'autoundwirtschaft.at',
      'autovisie.nl',
      'autoweek.nl',
      'avfbild.de',
      'awin.com',
      'axel-springer-akademie.de',
      'axel-voss-europa.de',
      'axelspringer-syndication.de',
      'axelspringer.com',
      'axelspringer.de',
      'axelspringer.hu',
      'axelspringer.pl',
      'azet.sk',
      'bams.de',
      'belvilla.com',
      'beobachter.ch',
      'beobachtertv.ch',
      'bike-bild.de',
      'bilanz-magazin.de',
      'bild.de',
      'bildconnect.de',
      'bilder.bild.de',
      'bildderfrau.de',
      'bildmobil.de',
      'blau-magazin.de',
      'blic.rs',
      'blikk.hu',
      'blogsociety.nl',
      'boerse-online.de',
      'bonial.com',
      'buecher.de',
      'businessinsider.de',
      'bz-berlin.de',
      'bz.de',
      'bz-jobs.de',
      'c.finanzen.net',
      'carwale.com',
      'casamundo.com',
      'clever-tanken.de',
      'code.bildstatic.de',
      'computerbild.de',
      'computerbildspiele.de',
      'daskapital.nl',
      'dnn-online.de',
      'dnn.de',
      'dzienniksport.pl',
      'dwdl.de',
      'ein-herz-fuer-kinder.de',
      'emarketer.com',
      'europeanvoice.com',
      'fakt.pl',
      'faz.de',
      'faz.net',
      'fernsehen.welt.de',
      'ffh.de',
      'ffn.de',
      'finanz.ru',
      'finanzen.ch',
      'finanzen.net',
      'flug.idealo.de',
      'foodbarn.com',
      'forbes.pl',
      'forbes.ru',
      'gashendel.nl',
      'gaspedaal.nl',
      'gehalt.de',
      'gehaltsvergleich.com',
      'geo.ru',
      'geolenok.ru',
      'glamouronline.hu',
      'gofeminin.de',
      'gooieneemlander.nl',
      'groupdeal.nl',
      'gruenderszene.de',
      'gutscheine.computerbild.de',
      'haarlemsdagblad.nl',
      'handelszeitung.ch',
      'i.auto-bild.de',
      'i.computer-bild.de',
      'idealo.de',
      'ijmuidercourant.nl',
      'ikiosk.de',
      'images.finanzen.net',
      'immergruen-medien.de',
      'immonet.de',
      'immoweb.be',
      'immowelt.de',
      'jaap.nl',
      'jobsite.co.uk',
      'kaufda.de',
      'komputerswiat.pl',
      'labanquesuisse.ch',
      'lacentrale.fr',
      'ladenzeile.de',
      'leidschdagblad.nl',
      'lesershop24.de',
      'lonny.com',
      'marketing.computerbild.de',
      'mazandmore.de',
      'meedia.de',
      'mediaimpact.de',
      'medienmagazin.de',
      'meinestadt.de',
      'meinprospekt.de',
      'metal-hammer.de',
      'musikexpress.de',
      'mylittleparis.fr',
      'n24.de',
      'newsweek.pl',
      'nin.co.rs',
      'noordhollandsdagblad.nl',
      'ok-magazine.ru',
      'onet.pl',
      'onmeda.de',
      'ozy.com',
      'partyguide.ch',
      'personalmarkt.de',
      'piwik.up.welt.de',
      'playpc.pl',
      'pme.ch',
      'politico.eu',
      'profession.hu',
      'radiohamburg.de',
      'radionrw.de',
      'relatieplanet.nl',
      'rem-track.bild.de',
      'resources-production.la.welt.de',
      'rollingstone.de',
      'rs2.de',
      'runtastic.com',
      'sat1.de',
      'schwarzkopf-stiftung.de',
      'schweizerbank.ch',
      'schweizerversicherung.ch',
      'scripts.finanzen.net',
      'seloger.com',
      'sonntagsmarkt-vertrieb.de',
      'speurders.nl',
      'sportauto.fr',
      'sportbild.bild.de',
      'sportbild.de',
      'sportdaten.sportbild.bild.de',
      'sports.pl',
      'sporttotal.tv',
      'spr.welt.de',
      'springer02.webtrekk.net',
      'static-finanzen.businessinsider.de',
      'static.businessinsider.de',
      'static.ein-herz-fuer-kinder.de',
      'static1.businessinsider.de',
      'static2.businessinsider.de',
      'static3.businessinsider.de',
      'static4.businessinsider.de',
      'static5.businessinsider.de',
      'static6.businessinsider.de',
      'stepstone.com',
      'stepstone.de',
      'students.at',
      'students.ch',
      'students.de',
      'stylebistro.com',
      'stylebook.de',
      'styles.finanzen.net',
      'techbook.de',
      'tele.ch',
      'telegraaf.nl',
      'telegraafvandaag.nl',
      'telesport.nl',
      'testbild.de',
      'tmg.nl',
      'tmssl.akamized.net',
      'totaljobs.com',
      'transfermarkt.de',
      'transfermarkt.tv',
      'travelbook.de',
      'tvrhet.hu',
      'tvstar.ch',
      'umzugsauktion.de',
      'upday.com',
      'usgang.ch',
      'vip-club.computer-bild.de',
      'vrouw.nl',
      'wams.de',
      'welt.de',
      'welt-kompakt.de',
      'weltn24.de',
      'werkenbijtmg.nl',
      'yad2.co.il',
      'yoc.de',
      'zanox.de',
      'zimbio.com'
    ],

    /**
       * Checks the given url against the central list object.
       *
       * @param {String} url - A full URL
       * @returns {Boolean} Blocked status
       *
       * @requires ../vendor/uri.js
       */

    isUrlBlocked: function (url) {
      var uri = new URI(url) // eslint-disable-line no-undef
      var domain = uri.domain()
      var list = hetzblocker.common.domainlist.listedDomains
      var i = 0

      while (i < list.length) {
        if (list[i] === domain) {
          return true
        }

        i += 1
      }

      return false
    }
  }
})()
