theme: "jekyll-theme-minimal"
title: "Hetzblocker Media Safeguard"
description: "A browser extension that is creating awareness of quality and responsibility in online media." 
logo: "logo.png"
show_downloads: "true"
