theme: "jekyll-theme-minimal"
title: "Hetzblocker"
description: "Hetzblocker is a browser extension for Chrome, Chromium and Firefox that blocks inflammatory media outlets, their publishers, and associated sites."
logo: "logo.png"
show_downloads: "true"
