name: "Tests"

on:
  - push

jobs:
  unit_tests:
    name: "Unit Tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"

      - name: "Cache node_modules"
        uses: "actions/cache@v2"
        with:
          path: "~/.npm"
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
          restore-keys: |
            ${{ runner.os }}-npm-
            ${{ runner.os }}-

      - name: "Setup NodeJS Environment"
        uses: "actions/setup-node@v1"
        with:
          node-version: "12.x"

      - name: "Install dependencies"
        run: "npm ci"

      - name: "Run Tests"
        run: "npm run test"
